name: Deploy Projects

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare website
        run: |
          mkdir _site

          # Personal Profile Page
          cp -r personal_profile_page/* _site/

          # Shared assets
          cp -r assets _site/

          # Compound Interest
          mkdir _site/compound-interest
          cp -r compound-interest/* _site/compound-interest/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
